import pandas as pd
# info: http://fileformats.archiveteam.org/wiki/23andMe
data = pd.read_csv("MyHeritage_raw_dna_data.csv",comment='#')

twentyColumns = ["rsid", "chromosome", "position", "genotype" ]
data.columns = twentyColumns
print("23andme uses your surname and last name in their data. Just press enter if I should go with John Smith instead")
surname = input("What is your surname? [John] :") or "John"
lastname = input("What is your last name? [Smith] :") or "Smith"

comments = """# This data file generated by 23andMe at: Mon Oct 13 19:07:27 2014
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier 
# (an rsid or an internal id), its location on the reference human genome, and the 
# genotype call oriented with respect to the plus strand on the human reference sequence.
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# Note that it is possible that data downloaded at different times may be different due to ongoing 
# improvements in our ability to call genotypes. More information about these changes can be found at:
# https://www.23andme.com/you/download/revisions/
# 
# More information on reference human assembly build 37 (aka Annotation Release 104):
# http://www.ncbi.nlm.nih.gov/mapview/map_search.cgi?taxid=9606
#
# rsid	chromosome	position	genotypeJ"""
filename = "genome_%s_%s_Full_20141013190727.txt"%(surname,lastname)
with open(filename,"w") as f:
    f.write(comments)

data.to_csv(filename,sep="\t",mode='a', index=False,header=False)
print(data.head())